new csv parser
Inist-CNRS/lodex pull request #112
Opened 2017-02-28 13:03 UTC by touv

try to add new loader...

2017-02-28 13:42 UTC, djhi requested changes

2017-02-28 13:42 UTC, djhi commented on package.json
> +    "ezs": "^1.1.3",
Please fix the version: don't use `^` nor `~`

2017-02-28 13:42 UTC, djhi commented on src/api/loaders/csv.js
> +  .pipe(ezs('CSVParse'))
Just a note but indenting would make this easier to read

2017-02-28 15:47 UTC, djhi requested changes
Can you prefix your PR's title with either `[WIP]` or `[RFR]` so that we know if/when you're done with it ?

2017-02-28 15:47 UTC, djhi commented on src/api/loaders/csv.js
> +  stream
Better but you should configure eslint for your IDE. This project has a specific eslint configuration with tabs made of 4 spaces :)

2017-02-28 17:15 UTC, touv commented on src/api/loaders/csv.js
> +  stream
ok, but where is the specific config file, I don't find any file like this https://github.com/Inist-CNRS/lodex-v1/blob/master/.eslintrc.js

2017-02-28 17:23 UTC, touv commented on src/api/loaders/csv.js
> +  stream
found !!! 
https://github.com/Inist-CNRS/lodex/blob/master/src/api/.eslintrc

2017-03-01 09:12 UTC, djhi approved these changes

2017-03-03 15:10 UTC, merged