Fix on model
Inist-CNRS/lodex pull request #1167
Opened 2020-12-14 14:32 UTC by JulienMattiussi

- Fix "Error" button alignment
- Fix URI multi column selection

2020-12-14 17:07 UTC, jdemangeon requested changes

2020-12-14 17:07 UTC, jdemangeon commented on src/app/js/fields/wizard/StepUriConcat.js
> +            console.log('EEE', event, value);
console spotted

2020-12-14 20:39 UTC, JulienMattiussi commented on src/app/js/fields/wizard/StepUriConcat.js
> +            console.log('EEE', event, value);
damned

2020-12-15 06:40 UTC, jdemangeon approved these changes

2020-12-15 06:40 UTC, merged