[RFR] Inist misc loaders
Inist-CNRS/lodex pull request #128
Opened 2017-03-08 09:01 UTC by touv

2017-03-08 09:12 UTC, djhi commented on docker-compose.yml
> +        - 8080:8080
why ?

2017-03-08 09:12 UTC, djhi commented on docker-compose.yml
> +    command: "--smallfiles"
:+1:

2017-03-08 09:13 UTC, djhi requested changes

2017-03-08 09:13 UTC, djhi commented on src/api/loaders/json.js
> +    .pipe(ezs('JSONParse', { separator: '*', ...config }))
please indent

2017-03-08 09:13 UTC, djhi commented on src/api/loaders/xml.js
> +          '/RDF/*',
please indent

2017-03-08 09:17 UTC, touv commented on docker-compose.yml
> +        - 8080:8080
oups, It's a patch to work on my pc

2017-03-09 08:33 UTC, djhi approved these changes

2017-03-09 08:33 UTC, merged