Added an information popup about the data merge before importing a new dataset
Inist-CNRS/lodex pull request #1285
Opened 2021-10-08 12:45 UTC by arimet

![modalInfo](https://user-images.githubusercontent.com/18294269/136559220-76ac4164-ae1c-4fc7-912a-38a5b7f2126f.gif)

2021-10-08 13:00 UTC, jdemangeon requested changes

2021-10-08 13:00 UTC, jdemangeon commented on cypress/support/datasetImportPage.js
> +    cy.wait(300);
You should wait for element visibility. Using wait is a bad practice

2021-10-08 13:00 UTC, jdemangeon commented on cypress/support/datasetImportPage.js
> +    cy.get('.progress', { timeout: 6000 }).should('not.exist');
Why 6000?

2021-10-08 13:00 UTC, jdemangeon commented on src/app/js/admin/upload/ConfirmUpload.js
> +export const ConfirmUploadComponent = ({
Can you rename this component? Because we don't known that it's a popup when reading "ConfirmUpload"

2021-10-08 13:00 UTC, jdemangeon commented on src/app/js/admin/upload/ConfirmUpload.js
> +ConfirmUploadComponent.propTypes = {
You miss isOpenPopup proptype. Moreover, as I previously said, you should rename the component with "popup" or "modal" keyword and rename this prop with a work like "isOpen"

2021-10-08 13:00 UTC, jdemangeon commented on src/app/js/admin/upload/ConfirmUpload.js
> +    const actions = [
Why do you use a variable for actions instead of putting them directly inside the jsx tree?

2021-10-08 13:00 UTC, jdemangeon commented on src/app/js/admin/upload/ConfirmUpload.js
> +            className="confirm"
Using classname for e2e tests is a bad practice, please use text inside it as selector instead

2021-10-08 13:00 UTC, jdemangeon commented on src/app/js/admin/upload/Upload.js
> +        if (useUrl) {
I don't see where the useUrl is declared :thinking: Moreover, this name seems to be too generic IMO

2021-10-08 13:00 UTC, jdemangeon commented on src/app/js/admin/upload/index.js
> +        OPEN_UPLOAD_POPUP: state => ({
Does this popup act as a global one? If not, you don't need to put it in redux. If yes, you should be sure that the component is "mounted" on the whole app container

2021-10-08 14:34 UTC, arimet commented on cypress/support/datasetImportPage.js
> +    cy.get('.progress', { timeout: 6000 }).should('not.exist');
This is an arbitrary value used in other tests

2021-10-08 14:34 UTC, arimet commented on src/app/js/admin/upload/ConfirmUpload.js
> +export const ConfirmUploadComponent = ({
Rename in PopupConfirmUpload

2021-10-08 14:35 UTC, arimet commented on src/app/js/admin/upload/ConfirmUpload.js
> +    const actions = [
I applied the same architecture as the popup containing the duplicate URIs

2021-10-08 14:36 UTC, arimet commented on src/app/js/admin/upload/index.js
> +        OPEN_UPLOAD_POPUP: state => ({
I changed the logic to use state and props!

2021-10-11 08:23 UTC, jdemangeon requested changes

2021-10-11 08:23 UTC, jdemangeon commented on babel.config.js
> +                        corejs: '2.6.12',
Hum... I'm not a big fan. Can you try again to remove it?

2021-10-11 08:23 UTC, jdemangeon commented on cypress/integration/publication.spec.js
> +            cy.wait(500);
Same remark about wait

2021-10-11 08:23 UTC, jdemangeon commented on src/app/js/admin/upload/PopupConfirmUpload.js
> +    const closePopup = () => {
Can you rename it to "handleClose"? (always prefix inner handler function with "handle")

https://jaketrent.com/post/naming-event-handlers-react
https://stackoverflow.com/questions/60048249/what-is-the-right-name-of-event-handler-onclick-or-handleclick

2021-10-11 08:23 UTC, jdemangeon commented on src/app/js/admin/upload/PopupConfirmUpload.js
> +export default compose(
You don't need compose here (because you only have one HOC)

2021-10-11 08:23 UTC, jdemangeon commented on src/app/js/admin/upload/Upload.js
> +            {useUrlForUpload && (
Can you put inner elements inside the same group? They have the same conditon (just put a fragment around them)

2021-10-11 09:30 UTC, jdemangeon approved these changes

2021-10-11 10:03 UTC, merged