14: Disable publish button if no fields
Inist-CNRS/lodex pull request #1289
Opened 2021-10-12 11:01 UTC by arimet

![publishbtn](https://user-images.githubusercontent.com/18294269/136943882-136e22f4-eae5-4855-8c8f-eb00f00f63fe.gif)

2021-10-14 15:17 UTC, jdemangeon requested changes

2021-10-14 15:17 UTC, jdemangeon commented on src/app/js/admin/publish/PublishButton.js
> +        allListFields.filter(f => f.name != 'uri').length > 0
Please use strict equality check.
Moreover, prefer using ".some()" instead of ".filter().length"

2021-10-14 15:17 UTC, jdemangeon commented on src/app/js/admin/publish/PublishButton.spec.js
> +    it.only('should return false if only field uri for publication', () => {
only spotted

2021-10-14 15:17 UTC, jdemangeon commented on src/app/js/admin/publish/PublishButton.spec.js
> +    it.only('should return false if only field uri for publication', () => {
Test title is not so clear to read

2021-10-14 15:31 UTC, arimet commented on src/app/js/admin/publish/PublishButton.js
> +        allListFields.filter(f => f.name != 'uri').length > 0
Thx, I totally forgot the existence of `some`

2021-10-15 15:14 UTC, jdemangeon approved these changes

2021-10-15 15:14 UTC, merged