16: Fix typo + republish dataset
Inist-CNRS/lodex pull request #1292
Opened 2021-10-14 15:08 UTC by arimet

2021-10-14 15:18 UTC, jdemangeon requested changes

2021-10-14 15:18 UTC, jdemangeon commented on src/app/js/admin/upload/sagas/uploadFile.js
> +        const { file } = yield race({
Why did you remove the cancel race condition?

2021-10-14 15:27 UTC, arimet commented on src/app/js/admin/upload/sagas/uploadFile.js
> +        const { file } = yield race({
Quand on ajoute un nouveau dataset, on change de page pour voir le résultat. Avec cette logique, il n'y a pas de raison de cancel l'upload si on change de page.

2021-10-15 15:13 UTC, jdemangeon commented on src/app/js/admin/upload/sagas/uploadFile.js
> +        const { file } = yield race({
OK, but if you leave the page before the upload finished, it will fail, i'm right?

2021-10-19 13:55 UTC, jdemangeon approved these changes

2021-10-19 13:55 UTC, merged