[WIP] Selenium smart wait
Inist-CNRS/lodex pull request #154
Opened 2017-03-14 17:57 UTC by ThieryMichel

2017-03-15 08:21 UTC, djhi requested changes

2017-03-15 08:21 UTC, djhi commented on src/app/e2e/home_published.spec.js
> +        const movieLabel = '.dataset-characteristics .property.movie .property_name';
I fail to see the value of declaring variables inside tests for the css selectors, except when they are used across several tests

2017-03-15 16:53 UTC, ThieryMichel commented on src/app/e2e/home_published.spec.js
> +        const movieLabel = '.dataset-characteristics .property.movie .property_name';
do you see that `.dataset-characteristics .property.movie .property_name` correspond to movieLabel ? me neither.

2017-03-15 22:05 UTC, djhi commented on src/app/e2e/home_published.spec.js
> +        const movieLabel = '.dataset-characteristics .property.movie .property_name';
I do but as you like

2017-03-16 10:20 UTC, djhi approved these changes

2017-03-16 10:21 UTC, merged