(WIP) Update node from 12 to 14
Inist-CNRS/lodex pull request #1702
Opened 2023-09-08 08:31 UTC by AlasDiablo

- [ ] General things to do
  - [x] Update docker file
  - [ ] Test LODEX with multiple data set and models
  - [ ] ...
- [ ] Bugs to fix
  - [ ] ResumableJS do not work with tsv and csv on node 14
  - [ ] ...

2023-09-20 08:21 UTC, touv requested changes

2023-09-20 08:21 UTC, touv commented on package.json
> +        "@recuperateur/async-busboy": "1.2.0",
Why isolate this fork in a separate repository, when in this version the objective is to bring external code into the main repository. I suggest moving this fork to the package directory

2023-09-22 16:23 UTC, touv approved these changes

2023-09-25 07:41 UTC, parmentf requested changes

2023-09-25 07:41 UTC, parmentf commented on packages/@recuperateur/async-busboy/package.json
> +    "url": "https://github.com/Recuperateur/async-busboy"
That link will not be maintained.
The README should be included in the directory.
Maybe the examples too.
The whole package in fact (with its LICENSE, and tests).

2023-09-25 15:06 UTC, parmentf approved these changes

2023-09-26 10:10 UTC, merged