LDA Chart and Routine
Inist-CNRS/lodex pull request #1797
Opened 2023-11-24 13:44 UTC by AlasDiablo

2023-11-29 15:14 UTC, touv requested changes
Je ne crois pas que ce graphiques  s'inscrire dans  la logique lodex notamment concernant les responsabilités de chaque composant : 

- Les formats graphiques affichent un flux de données standards à partir d’une URL et peuvent demander de filtrer ou trier ce résultat.
- Les pré calcul, transforment le jeu de données initial selon un algorithme particulier et créer un (ou plusieurs formats de sortie) et stocke le résultat en base
- Les routines récupèrent les données en base et adaptent éventuellement le résultat au format attendu par les graphiques 

Nous pouvons en discuter et échanger sur le design de cette feature

2023-12-04 12:33 UTC, JulienMattiussi approved these changes

2023-12-05 14:00 UTC, parmentf requested changes

2023-12-05 14:00 UTC, parmentf commented on src/app/custom/translations.tsv
> +r-clustered-precomputed_description	Retrieve precomputed data from precomputes like 'Lda-Segment' and display it in the Clustered chart	Récupér les données précalculées des précalculs comme 'Lda-Segm
```suggestion
r-clustered-precomputed_description	Retrieve precomputed data from precomputes like 'Lda-Segment' and display it in the Clustered chart	Récupère les données précalculées des précalculs comme 'Lda-Segment' et les affiche dans un Diagramme à barres groupées
```

2023-12-05 14:00 UTC, parmentf commented on src/app/custom/translations.tsv
> +formatClusteredChartDescription	Displays several bar charts depending on the category of the element and its weight	Affiche plusieurs diagrammes à barres en fonction de la catégorie de l'élément et d
```suggestion
formatClusteredChartDescription	Displays several bar charts depending on the category of the element and its weight	Affiche plusieurs diagrammes à barres en fonction de la catégorie de l'élément et de son poids
```

2023-12-05 14:00 UTC, parmentf commented on workers/routines/clustered-precomputed.ini
> +[reducing]
Maybe you can simplify using [`[dedupe]`](https://inist-cnrs.github.io/ezs/#/plugin-core?id=dedupe)

2023-12-06 09:06 UTC, parmentf approved these changes
`dedupe` seems to yield warnings in the console at each duplicate, that may not be wanted.
Let's wait a better version of `dedupe`.

2023-12-06 09:07 UTC, merged