theme inist adaption pour lodex 14
Inist-CNRS/lodex pull request #1886
Opened 2024-02-05 16:21 UTC by HeleneCreusot

fevrier 2024 update list

- [ ] index.html restore class container for header (as root and footer)
- [ ] notice : new items links in footer
- [ ] css/inist.css refactor breadcrumb's links (new files systeme lodex introduce dir themes)
- [ ] css/inist.css and index.html : delete import loader.css obsolet for lodex 14 theme colors
- [ ] index.html : delete link aphrodite.css obsolet for lodex 14 theme colors
- [ ] delete dir image and contains : replace by img

2024-02-06 07:03 UTC, AlasDiablo requested changes

2024-02-06 07:03 UTC, AlasDiablo commented on src/themes/inist/index.html
>        <div id="logos">
Il me semble qu'il y a eu un changement au niveau des logo CNRS à voir s'il s'applique ici.

2024-02-06 07:41 UTC, HeleneCreusot commented on src/themes/inist/index.html
>        <div id="logos">
le logo est à jour
src : https://intranet.cnrs.fr/Cnrs_pratique/communiquer/ress/Documents/CNRS_CHARTE_GLOBALE_JANV24.pdf

2024-02-06 12:25 UTC, HeleneCreusot commented on src/themes/inist/index.html
>        <div id="logos">
ok, non il n'est pas à jour. MAIS cette demande ne concerne pas la présente PR

2024-02-07 06:47 UTC, AlasDiablo approved these changes
C'est bon pour moi

2024-02-12 08:29 UTC, merged