Updating themes system
Inist-CNRS/lodex pull request #1999
Opened 2024-05-14 09:43 UTC by AlasDiablo

2024-05-15 07:59 UTC, parmentf commented on src/api/models/themes.js
> +// --- TypeScript without TypeScript (Required an ide with TypeScript support)
<!-- Praises highlight something positive. Try to leave at least one of these comments per review. Do not leave false praise (which can actually be damaging). Do look for something to sincerely praise.  -->
**praise:** ‏I like that!

2024-05-15 07:59 UTC, parmentf commented on src/api/models/themes.js
> +// --- TypeScript without TypeScript (Required an ide with TypeScript support)
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion (non-blocking):** Add the `checkJs` setting to `.vscode/settings.json`

See https://github.com/Inist-CNRS/ezs/blob/master/.vscode/settings.json#L2‏

2024-05-23 14:01 UTC, parmentf requested changes

2024-05-23 14:01 UTC, parmentf commented on src/api/models/themes.js
>  const availableThemes = new Map();
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Check it's still useful, if not, remove it.

Warning: deprecated functions may use it.

2024-05-24 07:24 UTC, parmentf approved these changes

2024-05-30 06:15 UTC, touv approved these changes

2024-05-30 06:15 UTC, merged