Treemap format
Inist-CNRS/lodex pull request #2021
Opened 2024-06-07 06:38 UTC by AlasDiablo

2024-06-10 13:41 UTC, leogail reviewed
Je ne sais pas où les traductions apparaissent et s'il faut les traduire ou non

2024-06-10 13:41 UTC, leogail commented on src/app/custom/translations.tsv
> +"binary"	"Binary"	"Binary"
**question (if-minor):** Faut-il les traduire ?

2024-06-11 07:11 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapView.js
> +            }
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Just add

It's a set, just use  `nodes.add(value.parent)`.
```suggestion
            if (value.parent) {
                nodes.add(value.parent);
            }
```

2024-06-11 07:11 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapView.js
> +        const tmpData = new Map();
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏I would look for a better variable name

Like `name2parentSize`.

2024-06-11 07:11 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapView.js
> +                }
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** I would make a function like `initId` to make it clearer.
```js
const initId = (name) => {
  if (!ids.has(name)) {
    ids.set(name, ++idIncrement);
  }
};
```

2024-06-11 07:11 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapView.js
> +        data.values.forEach((value) => {
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** I would have used a map or a reduce

Of course, that would have required looping twice, but... I think it would be clearer.‏

2024-06-11 07:11 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapView.js
> +        let outputData = new Map();
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Choose a better name for `outputData`

2024-06-11 07:11 UTC, parmentf commented on src/app/custom/translations.tsv
> +"binary"	"Binary"	"Binary"
Excellente question.
Personnellement, *treemap* me parle plus que *carte proportionnelle*, même si la traduction semble mieux refléter ce dont on parle.
C'est un terme classique en dataviz.

2024-06-12 12:48 UTC, parmentf requested changes

2024-06-12 12:48 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapData.js
> +    filteredNodes;
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** Precise in comments that filtered nodes are not leaves‏

2024-06-12 12:48 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapData.js
> +     * Transformed routine data into transformable data
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏
```suggestion
     * Transform routine data into transformable data
```

2024-06-12 12:48 UTC, parmentf commented on src/app/js/formats/vega/component/tree-map/TreeMapData.js
> +        for (let rawNodeAndLeaf of this.rawNodesAndLeaves) {
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** Use destructuring‏

2024-06-13 15:30 UTC, parmentf approved these changes

2024-06-13 15:30 UTC, touv approved these changes

2024-06-13 15:30 UTC, merged