Add an EJS Format
Inist-CNRS/lodex pull request #2047
Opened 2024-06-18 08:10 UTC by AlasDiablo

2024-06-18 12:42 UTC, touv requested changes
Merci, c’est bon début, il reste quelques détails pour que ce format puisse être compris facilement par des non experts, j’ajouterais :   

- les traductions pour le nom et la description du format
- un texte explicatif au dessus de l’éditeur, pour expliquer ce qui attendu, cad un template HTML respectant la syntaxe EJS
- La zone de saisie ne devrait pas être vide par défaut, j’y mettrai un exemple qui fonctionne avec la majorité des routines. Exemple :

```
<%# Template EJS de mis en forme des données retournées par une routine %>
<table>
    <thead>
    <tr>
      <th>ID</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <% formatData.forEach((value) => { %>
    <tr>
        <td><%= value._id %></td>
        <td><%= value.value %></td>
    </tr>
  <% }); %>    
  </tbody>
</table>

```
- je n’utiliserai formatData pas comme nom de variable principale, mais root.values comme dans le format JSONDebug, j'ajouterai une référence à ce format pour inviter à découvrir et visualiser les données qui devront être mise en forme par le template
- en plus de formatData, j’atouterais formatTotal (root.total) et formatError (root.Error), en les renommant de manière cohérente par rapport à formatData
	
- En cas d’erreur, j’afficherai un message dans la console du navigateur

2024-06-19 13:53 UTC, parmentf requested changes

2024-06-19 13:53 UTC, parmentf commented on src/app/custom/translations.tsv
> +"ejs_variable_list"	"You can use these variables to access to the data and utils:"	"Vous pouvez utiliser ces variables pour accédez au données et au utilitaire :"
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
"ejs_variable_list"	"You can use these variables to access to the data and utils:"	"Vous pouvez utiliser ces variables pour accéder aux données et aux utilitaires :"
```

2024-06-19 13:53 UTC, parmentf commented on src/app/custom/translations.tsv
> +"ejs_data"	"Variable containing the routine data"	"Variable contentent les données de la routine"
```suggestion
"ejs_data"	"Variable containing the routine data"	"Variable contenant les données de la routine"
```

2024-06-19 13:53 UTC, parmentf commented on src/app/custom/translations.tsv
> +"ejs_lodash"	"Variable containing the Lodash function"	"Variable contentent les fonction de Lodash"
```suggestion
"ejs_lodash"	"Variable containing the Lodash function"	"Variable contenant les fonctions de Lodash"
```

2024-06-19 13:53 UTC, parmentf commented on src/app/js/formats/text/ejs/EJSAdmin.js
> +    template: `<% /* Ceci est un exemple qui prendre en compte plusieurs types de donnée. */ %>
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** Take fixed content from `example.ejs` back into this file‏

2024-06-19 13:53 UTC, parmentf commented on src/app/js/formats/text/ejs/example.ejs
> +<% /* Vous pouviez changer les données dans l'aperçu pour voir les different possibilité */ %>
```suggestion
<% /* Ceci est un exemple qui peut prendre en compte plusieurs types de données. */ %>
<% /* Vous pouvez changer les données dans l'aperçu pour voir les différentes possibilités */ %>
```

2024-06-19 13:53 UTC, parmentf commented on src/app/js/formats/text/ejs/example.ejs
> +<% /* On vérifie si les données ne sont pas une list */ %>
```suggestion
<% /* On vérifie si les données ne sont pas une liste */ %>
```

2024-06-19 13:53 UTC, parmentf commented on src/app/js/formats/text/ejs/example.ejs
> +<% /* We check if the data is a list with _id / value pair */ %>
```suggestion
<% /* On vérifie si les données sont une liste de paires _id / value */ %>
<% /* We check if the data is a list of _id / value pairs */ %>
```

2024-06-19 13:53 UTC, parmentf commented on src/app/js/formats/text/ejs/example.ejs
> +    <% /* display data in table form */ %>
```suggestion
    <% /* display data in table format */ %>
```

2024-06-19 13:53 UTC, parmentf commented on src/app/js/formats/text/ejs/example.ejs
> +<% /* We check if the data is a list with source / target / weight tuple */ %>
```suggestion
<% /* On vérifie si les données sont une liste de tuples source / target / weight */ %>
<% /* We check if the data is a list with source / target / weight tuples */ %>
```

2024-06-19 13:53 UTC, parmentf commented on src/app/js/formats/text/ejs/example.ejs
> +    <% /* display data in table form */ %>
```suggestion
    <% /* display data in table format */ %>
```

2024-06-20 15:00 UTC, touv commented
L'exemple par défaut fonctionne parfaitement avec tous les formats produits par les routines. C'est un avantage. 
Mais du coup, il est complexe on, s’éloigne d'un exemple simple et facile à comprendre.

Ne serait-il pas possible d'avoir des exemples séparés ?
On afficherait un exemple simple prévu pour fonctionner avec { _id, value } et  les autres seraient chargés en cliquant sur un lien explicite.

2024-06-21 07:01 UTC, parmentf requested changes

2024-06-21 07:01 UTC, parmentf commented on src/app/custom/translations.tsv
> +"ejs_variable_list"	"Data from a routine is displayed using an HTML template based on EJS syntax. You can use these variables to access to the data and utils:"	"L’affichage des données en provenance
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
"ejs_variable_list"	"Data from a routine is displayed using an HTML template based on EJS syntax. You can use these variables to access data and utils:"	"L’affichage des données en provenance d’une routine est réalisé à l’aide d’un template HTML utilisant la syntaxe EJS. Vous pouvez utiliser ces variables pour accéder aux données et aux utilitaires :"
```

2024-06-21 12:56 UTC, merged