[WIP] Add characteristics
Inist-CNRS/lodex pull request #208
Opened 2017-03-27 14:05 UTC by ThieryMichel

2017-03-29 16:08 UTC, djhi requested changes

2017-03-29 16:08 UTC, djhi commented on makefile
> +	# NODE_ENV=test ${MAKE} build-frontend
woops

2017-03-29 16:08 UTC, djhi commented on src/app/js/i18n/translations/en.js
> +    'add-field-to-resource': 'add field',
change dashes for underscores and loose the quotes

2017-03-29 16:08 UTC, djhi commented on src/app/js/lib/DialogButton.js
> +export const DialogButtonComponent = ({
I would rename this component to `ButtonWithDialog`. I first thought that it was a button for inside the dialog

2017-03-29 16:08 UTC, djhi commented on src/app/js/public/dataset/Dataset.js
> +                <CardActions style={styles.actions}>
Isn't this only available to Julia ?

2017-03-30 08:53 UTC, ThieryMichel commented on src/app/js/public/dataset/Dataset.js
> +                <CardActions style={styles.actions}>
It's the AddCharacteristic responsibility, to show itself or not.

2017-03-30 09:42 UTC, djhi approved these changes

2017-03-30 09:42 UTC, merged