Theme config autocomplete
Inist-CNRS/lodex pull request #2094
Opened 2024-07-17 05:45 UTC by AlasDiablo

resolve #2092

2024-07-17 08:50 UTC, HeleneCreusot commented
[4f58b48](https://github.com/Inist-CNRS/lodex/pull/2094/commits/4f58b487400aa7bd3bc6d00ed7896e21047a4082) Le nom du thème est Voscouleurs (sans espace) et je décide finalement qu'il ne doit pas être traduit et sera nommé Voscouleurs en anglais aussi.
C'est mon choix d'autrice mais ça se discute
@touv @parmentf @AlasDiablo

2024-07-17 15:24 UTC, parmentf requested changes

2024-07-17 15:24 UTC, parmentf commented on src/app/js/admin/configTenant/ConfigTenantForm.js
> +            const clonedConfig = _.cloneDeep(JSON.parse(configTenant));
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** You should remove `_.cloneDeep` and rename `clonedConfig`...‏

2024-07-18 11:46 UTC, parmentf approved these changes

2024-07-18 11:46 UTC, merged