to avoid that field contains '+' et '/' characters
Inist-CNRS/lodex pull request #223
Opened 2017-03-30 10:26 UTC by touv

because base64 contains this characters https://en.wikipedia.org/wiki/Base64 and we cannot use them in web semantic export formats.

2017-03-30 13:07 UTC, ThieryMichel requested changes

2017-03-30 13:07 UTC, ThieryMichel commented on src/api/services/generateUid.js
> +        resolve(result.toString('base64').replace(/[+/]/g, 'z'));
you need to escape the `/`

2017-03-30 13:26 UTC, touv commented on src/api/services/generateUid.js
> +        resolve(result.toString('base64').replace(/[+/]/g, 'z'));
you're right, JS is so fun that this syntaxe works too ;-)

2017-04-03 08:19 UTC, ThieryMichel approved these changes

2017-04-03 08:20 UTC, merged