fix(theme istex): readme, css, img L14.0.68
Inist-CNRS/lodex pull request #2282
Opened 2024-12-18 10:41 UTC by HeleneCreusot

update readme, add new logo svg, css

2024-12-20 12:10 UTC, touv requested changes

2024-12-20 12:10 UTC, touv commented on src/app/custom/themes/istex/img/header/istex.svg
Est-ce normal que les premières lettres soient en blanc et non bleu ?

2024-12-20 13:30 UTC, HeleneCreusot commented on src/app/custom/themes/istex/img/header/istex.svg
oui, c'est le même logo que search.istex et services.istex. C'est bien dans la charte

2024-12-20 14:10 UTC, HeleneCreusot reviewed
oui il est conforme à la charte graphique

2025-01-08 10:49 UTC, touv approved these changes

2025-01-08 10:49 UTC, merged