Feat(admin): Provide ability to delete multiple fields at the same time
Inist-CNRS/lodex pull request #2292
Opened 2024-12-20 10:49 UTC by arnault-dev

Closes #2187 

https://github.com/user-attachments/assets/08270f98-d469-45b5-8d16-90834c110cbd

2025-01-06 08:13 UTC, ThieryMichel requested changes

2025-01-06 08:13 UTC, ThieryMichel commented on src/app/custom/translations.tsv
> +"select_field"	"Select field"	"Sélectionner le champ"
nit-pick: missing empty line at the end of the file

2025-01-06 08:13 UTC, ThieryMichel commented on src/app/js/fields/sagas/removeFieldList.js
> +            const { error } = yield call(fetchSaga, request);
Wouldn't it be better to have an api route to delete many fields?
What if  the selected fields contains fields that depends on another selected field ? You could refuse to delete it even though it should get accepted.

2025-01-07 16:22 UTC, arnault-dev commented on src/app/js/fields/sagas/removeFieldList.js
> +            const { error } = yield call(fetchSaga, request);
Seen with previous dev: this is handled by remove field by ID

2025-01-09 09:40 UTC, ThieryMichel approved these changes

2025-01-09 09:40 UTC, merged