:construction:  [WIP] Exporter Istex Query
Inist-CNRS/lodex pull request #307
Opened 2017-04-28 16:27 UTC by QuanticPotatoes

2017-05-02 07:29 UTC, djhi submitted a review, later dismissed

2017-05-02 07:29 UTC, djhi commented on src/api/exporters/exportIstex.js
> +/*
Don't keep commented out code

2017-05-02 07:29 UTC, djhi commented on src/api/exporters/ezsLocals.js
> +      .filter(({ status }) => status !== VALIDATED)
weird indentation

2017-05-02 07:29 UTC, djhi commented on src/api/exporters/ezsLocals.js
> -//             '@type': 'https://www.w3.org/TR/xmlschema-2/#anyURI',
commented out code

2017-05-02 07:29 UTC, djhi commented on src/api/exporters/ezsLocals.js
> +      data.uri.indexOf('http://') !== 0 && data.uri.indexOf('https://') !== 0
format: weird indentation

2017-05-02 07:29 UTC, djhi commented on src/api/exporters/ezsLocals.js
> +      .filter(field => field.format && field.format.name === 'istex')
same

2017-05-02 07:29 UTC, djhi commented on src/api/exporters/ezsLocals.js
> +        feed.send(data);
here too

2017-05-02 07:29 UTC, djhi commented on src/api/exporters/ezsLocals.js
> +        jsonld.toRDF(data, { format: 'application/nquads' }).then(
here again

2017-05-02 12:08 UTC, QuanticPotatoes commented
The weird indentation is generate by my eslint formatter plugin.
I'll see if i can solve this problem.

2017-05-03 12:16 UTC, parmentf requested changes
Adapt the `config.json` to the new name `extendednquads`.

2017-05-03 12:16 UTC, parmentf commented on config.json
> +        "istex",
Shouldn't it be `extendednquads` instead?

2017-05-10 15:28 UTC, parmentf approved these changes

2017-05-17 16:14 UTC, merged