[WIP] Link function
Inist-CNRS/lodex pull request #31
Opened 2017-01-31 12:05 UTC by djhi

- [x] Refactored transformations to introduce context
- [ ] Applied transformations by stages (pre, post)
- [ ] Implemented `getDocumentUri`

2017-02-01 16:22 UTC, ThieryMichel requested changes

2017-02-01 16:22 UTC, ThieryMichel commented on src/api/controller/api/publish.js
> +    while (handled < count) {
Should'nt the uri be added at the start, and then th Link operation could be executed at the same time as all the other.

2017-02-02 08:22 UTC, djhi commented on src/api/controller/api/publish.js
> +    while (handled < count) {
I'm not sure, can't it be the result of other transformed fields too ?

2017-02-02 08:25 UTC, djhi commented on src/api/controller/api/publish.js
> +    while (handled < count) {
Which also means it shouldn't be added automatically as the first field too btw

2017-02-03 11:35 UTC, djhi commented
Superceded by #33

2017-02-03 11:35 UTC, closed without merging