[WIP] Add Danger Zone
Inist-CNRS/lodex pull request #402
Opened 2017-07-11 15:41 UTC by QuanticPotatoes

2017-07-18 08:53 UTC, touv approved these changes

2017-07-19 08:23 UTC, parmentf commented on src/app/js/admin/Appbar/index.js
> +            {isLoggedIn && <Settings />}
Why call it _Settings_? Why not `DangerZone` ?

2017-07-19 09:33 UTC, parmentf requested changes
Sort functions by route in user/index.js

2017-07-19 09:33 UTC, parmentf commented on src/app/js/user/index.js
> +export const getClearPublishedRequest = state => getRequest(state, {
Sort these functions by route, please.

2017-07-19 12:16 UTC, parmentf approved these changes

2017-07-19 12:26 UTC, merged