[WIP] Ssr
Inist-CNRS/lodex pull request #468
Opened 2017-11-14 17:08 UTC by ThieryMichel

2017-11-20 17:48 UTC, fzaninotto requested changes
To be rebased when previous PR is merged

2017-11-20 17:48 UTC, fzaninotto commented on src/api/controller/front/index.js
> +                const store = configureStoreServer(
Can't you export that block to make it testable, and reduce the size of the current file ?

2017-11-20 17:48 UTC, fzaninotto commented on src/api/controller/index.js
> +import path from 'path';
not used?

2017-11-20 17:48 UTC, fzaninotto commented on src/api/models/publishedDataset.js
> +    collection.countByFacet = (field, value) =>
async?

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/admin/App.js
> +            <title>{/https?:\/\/([\w-]+)/.exec(process.env.EZMASTER_PUBLIC_URL)[1]}</title>
please extract to standalone function

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/admin/clear/sagas.js
> +export default [watchClearDatasetRequest, watchClearPublishedRequest];
please revert

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/admin/preview/sagas.js
> -export default function* () {
same, please revert if not necessary

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/admin/removedResources/sagas/index.js
> +export default [
same

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/admin/sagas.js
> +    yield all(fieldsSaga.map(fork));
please revert here and down in this file

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/admin/upload/sagas/index.js
> +export default [
revert

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/fields/sagas/index.js
> +export default [
please revert

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/i18n/sagas/index.js
> +export default [
please revert

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/lib/queryStringToLiteral.js
> +export default (queryString = '') =>
you should use a module like `qs` for that.

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/public/App.js
> +            <title>{/https?:\/\/([\w-]+)/.exec(process.env.EZMASTER_PUBLIC_URL)[1]}</title>
please move to external function

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/public/Home.js
> +                        <title>{/https?:\/\/([\w-]+)/.exec(process.env.EZMASTER_PUBLIC_URL)[1]}</title>
please move to external function

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/public/characteristic/sagas/index.js
> +export default [
please revert

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/public/overview/Overview.js
> +                                                      columns.filter(
please refactor to avoid repetition

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/public/resource/Detail.js
> +                <title>{/https?:\/\/([\w-]+)/.exec(process.env.EZMASTER_PUBLIC_URL)[1]} - {sharingTitle || resource.uri}</title>
please extract

2017-11-20 17:48 UTC, fzaninotto commented on src/app/js/public/resource/sagas/index.js
> +export default [
please revert

2017-11-21 10:54 UTC, ThieryMichel commented on src/app/js/admin/preview/sagas.js
> -export default function* () {
done

2017-11-21 17:15 UTC, fzaninotto approved these changes

2017-11-21 17:16 UTC, merged