[RFR] better presentation for resource page
Inist-CNRS/lodex pull request #49
Opened 2017-02-08 14:42 UTC by ThieryMichel

2017-02-08 14:57 UTC, djhi commented
screenshot ?

2017-02-08 15:04 UTC, ThieryMichel commented
![capture du 2017-02-08 16 02 32](https://cloud.githubusercontent.com/assets/4034399/22742755/3b9d714e-ee18-11e6-9fdb-ae8681f59aea.png)

2017-02-08 15:06 UTC, djhi requested changes

2017-02-08 15:06 UTC, djhi commented on src/app/js/resource/Resource.js
> +                        <HomeIcon />
apply flex box and align-items to center the icon vertically

2017-02-08 15:07 UTC, djhi requested changes

2017-02-08 15:07 UTC, djhi commented on src/app/js/resource/Resource.js
> +                        <HomeIcon />
same

2017-02-09 10:43 UTC, djhi approved these changes

2017-02-09 10:43 UTC, merged