[WIP] add Exportable compoennt to allow to save chart as png
Inist-CNRS/lodex pull request #503
Opened 2017-12-05 17:17 UTC by ThieryMichel

2017-12-05 17:22 UTC, fzaninotto commented
needs rebase

2017-12-06 17:17 UTC, fzaninotto requested changes

2017-12-08 14:18 UTC, ThieryMichel commented on src/app/js/lib/convertHtmlToPng.js
> +    html2Canvas(element).then(canvas => canvas.toDataURL());
Added a catch where the function is used.

2017-12-08 16:01 UTC, fzaninotto approved these changes

2017-12-08 16:01 UTC, merged