[WIP] to use istex api v5
Inist-CNRS/lodex pull request #552
Opened 2018-01-09 15:14 UTC by touv

2018-01-10 16:42 UTC, ThieryMichel requested changes

2018-01-10 16:42 UTC, ThieryMichel commented on src/api/loaders/corpus.js
> +        .pipe(ezs('debug'));
debug ?

2018-01-11 14:14 UTC, touv commented on src/api/loaders/corpus.js
> +        .pipe(ezs('debug'));
of course !

2018-01-11 14:47 UTC, ThieryMichel approved these changes

2018-01-11 14:47 UTC, merged