[WIP] Api file import
Inist-CNRS/lodex pull request #6
Opened 2017-01-19 17:32 UTC by ThieryMichel

2017-01-20 12:57 UTC, djhi commented on src/app/js/home/Home.js
> +import Upload from './Upload';
If #7 is merged first, you'll be able to put this Upload component on the Admin component

2017-01-24 08:31 UTC, djhi requested changes

2017-01-24 08:31 UTC, djhi commented on package.json
> +    "async-busboy": "^0.3.3",
replace `^` with `~`

2017-01-24 08:36 UTC, djhi requested changes

2017-01-24 08:36 UTC, djhi commented on makefile
> +<<<<<<< HEAD
oops

2017-01-24 08:36 UTC, djhi commented on src/api/controller/api/index.js
> +        console.log('closing db');
debug spotted

2017-01-24 14:54 UTC, djhi commented on src/api/controller/api/index.js
> +app.use(async (ctx, next) => {
Should be put in a middleware file to allow testing. Not very important

2017-01-24 15:00 UTC, djhi requested changes

2017-01-24 15:00 UTC, djhi commented on src/api/models/dataset.js
> +
extra line

2017-01-24 15:00 UTC, djhi commented on src/app/.eslintrc
>          "react/jsx-filename-extension": ["warn", { "extensions": [".js", ".jsx"] }],
We don't need react on the API

2017-01-24 15:00 UTC, djhi commented on src/app/js/admin/upload/Upload.js
> +        style={{
put styles in an object with keys for each "classes". Make the react code easier to read

2017-01-24 15:00 UTC, djhi commented on src/app/js/admin/upload/index.js
> +export const uploadFilePending = createAction(UPLOAD_FILE_PENDING);
You don't need pending. Just use `UPLOAD_FILE` to set the loading state in the reducer

2017-01-24 17:02 UTC, ThieryMichel commented on src/app/js/admin/upload/index.js
> +export const uploadFilePending = createAction(UPLOAD_FILE_PENDING);
I use it to display a spinner now.

2017-01-24 17:49 UTC, djhi requested changes

2017-01-24 17:49 UTC, djhi commented on src/app/js/admin/parsing/ParsingResult.js
> +bindActionCreators({
why the `bindActionCreators` ? Just pass an object

2017-01-24 17:49 UTC, djhi commented on src/app/js/admin/upload/Upload.js
> +        style={{
extract those styles outside the component in the same file with a key for each "classes", it'll make the jsx more readable

2017-01-24 17:49 UTC, djhi commented on src/app/js/admin/upload/index.js
> +export const UPLOAD_FILE_PENDING = 'UPLOAD_FILE_PENDING';
You don't need pending, set the status to 'pending' when `UPLOAD_FILE` is triggered.

2017-01-24 17:50 UTC, djhi commented
Also can you clean the commits ?

2017-01-25 09:47 UTC, djhi requested changes

2017-01-25 09:47 UTC, djhi commented on src/app/js/admin/upload/Upload.js
> +const mapsStateToProps = state => ({
```js
const mapsStateToProps = ({ upload }) => upload;
```

2017-01-25 09:50 UTC, djhi requested changes

2017-01-25 09:50 UTC, djhi commented on src/app/js/admin/upload/uploadFileSaga.js
> +        yield put(uploadFileError(error.message));
pass the error directly to be FSA compliant and eventually only use the message in the reducer

2017-01-25 09:50 UTC, djhi commented on src/app/js/admin/upload/uploadFileSaga.js
> +        yield put(uploadFileError(error.message));
Not doing so prevent us to use a saga or middleware for global error handling

2017-01-25 09:59 UTC, djhi requested changes

2017-01-25 09:59 UTC, djhi commented on src/app/js/admin/upload/Upload.js
> +    ...upload,
you don't need `...`, just return `upload` directly

2017-01-25 10:09 UTC, djhi approved these changes

2017-01-25 10:14 UTC, merged