[WIP] Traitement sur le format ressource
Inist-CNRS/lodex pull request #662
Opened 2018-04-17 14:38 UTC by chaBiselx

2018-04-18 13:57 UTC, chaBiselx commented
lorsque que l'on clique sur un lien en interne, nous observons un warnig dans les logs du navigateur (voir message à la fin du commentaire). Ce message ne devrait pas apparaitre puisqu'on utilise la même méthode qu'avant la création de la branche.

 Warning: A path must be pathname + search + hash only, not a full URL like "http://localhost:3000/ark:/67375/Q4W-1MC8ZQ2Z-F"

2018-04-19 13:30 UTC, parmentf requested changes

2018-04-19 13:30 UTC, parmentf commented on src/app/js/formats/shared/LodexResource.js
> +    let getFullResourceUriDomain = getFullResourceUri({ uri: id }).replace(
This variable is a string, not a function, it should not contain a verb (`get`).
I would rename it to `fullResourceUriDomain`.

2018-04-19 13:30 UTC, parmentf commented on src/app/js/formats/shared/LodexResource.js
> +    const content = () => {
Why make `content` a function?
It could be a variable containing a JSX structure. I think it would work as well.

2018-04-19 13:30 UTC, parmentf commented on src/app/js/formats/shared/LodexResource.js
> +    if (urlDomain == getFullResourceUriDomain) {
Maybe clearer using `if (!isLocalURL(id)) {`
(isLocalURL already exists in [src/common/uris.js](https://github.com/Inist-CNRS/lodex/blob/master/src/common/uris.js#L8-L13))

What do you think?

2018-04-20 13:45 UTC, parmentf approved these changes

2018-04-20 13:46 UTC, merged