[WIP] Sparql pie chart
Inist-CNRS/lodex pull request #665
Opened 2018-05-02 12:27 UTC by chaBiselx

2018-05-03 20:45 UTC, touv requested changes
Attention, des formats "graphiques" existent déjà dans lodex, pourquoi en recréer spécialement pour les requêtes SPARQL ? D'un point de vue UX ça me pose bcp de questions. Si on a un besoin de graphiques pour des requêtes SPARQL, (à partir d'un cas d'usage précis). Il faut regarder à réutiliser les formats graphiques existants en utilisant par exemple des routines et des sous-formats (comme les listes)

2018-05-09 15:43 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlAdmin.js
> +class SparqlTextAdmin extends Component {
Oups. J'aurais dit `SparqlPieAdmin`.

2018-05-09 16:00 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlAdmin.js
> +                <SelectField
Je ne sais pas pourquoi, mais on ne voit pas ce qu'on a sélectionné.
Ce serait bien aussi de pouvoir dire qu'on ne veut pas trier...

2018-05-09 16:02 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlRequest.js
> +import React, { Component } from 'react';
Il faudra sans doute mettre ce fichier en commun au niveau supérieur (répertoire `sparql`), j'ai l'impression que c'est le même que dans SparqlTable.

2018-05-09 16:04 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlRequest.js
> +                    <p style={styles.message}>{polyglot.t('sparql_error')}</p>
Il faudra mettre une traduction du genre `Nous ne sommes pas en mesure d'afficher les données du serveur distant.`.
Utile quand par le plus grand des hasards un SPARQL EndPoint change ses autorisations CORS.

2018-05-09 16:09 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlView.js
> +export class SparqlText extends Component {
Copier-coller intempestif? On n'est plus dans `SparqlText`, mais dans `SparqlPieChart`, et dans le fichier `SparqlView.js`.

Il faudrait se mettre d'accord sur ce qu'on fabrique dans ce fichier.

2018-05-09 16:11 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlView.js
> +            const requestText = resource[field.name];
Je chipote mais plus bas il y a un paramètre nommé `sparqlRequest` (ce qui est correct en anglais), on devrait nommer cette variable `textRequest`, à l'anglaise aussi.

2018-05-09 16:14 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlView.js
> +            for (let i of formatData.results.bindings) {
J'aurais plutôt vu cette opération au niveau de `SparqlRequest`, puisque les formats graphiques prennent des données similaires.

Ça permettrait même d'utiliser [global-pie-chart](https://github.com/Inist-CNRS/lodex/tree/master/src/app/js/formats/distributionChart/global-pie-chart) pour afficher les données, sans avoir à tout réécrire.

2018-05-09 16:18 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlView.js
> +        const requestPagination = constructURL + ' LIMIT ' + sparql.maxValue;
De toute façon, pas de pagination dans un camembert.

2018-05-09 16:20 UTC, parmentf commented on src/app/js/formats/sparql/SparqlPieChart/SparqlView.js
> +    SparqlRequest(({ field, resource, sparql }) => {
J'ai l'impression que cette fonction est générique pour toute requête SPARQL, non?
Pourquoi ne pas l'intégrer directement à SparqlRequest ?

2018-05-23 07:26 UTC, closed without merging