[WIP] New format Lodex field
Inist-CNRS/lodex pull request #671
Opened 2018-05-25 08:56 UTC by chaBiselx

2018-05-31 11:42 UTC, chaBiselx commented
il manque la gestion d'erreur

2018-06-09 08:01 UTC, touv commented on src/api/exporters/exportJson.js
> +            ezs((resource, output) => {
Don't use a inline function. It's should be better to create a standalone function in the ./statements/ directory. You'll be able to write a unit test, and to externalize the function.

2018-06-14 13:18 UTC, parmentf commented on src/api/exporters/exportJson.js
> +exporter.label = 'json';
Maybe create a new translation key, because this one is translated to "JSON - with an array".

2018-06-15 16:06 UTC, parmentf requested changes

2018-06-15 16:06 UTC, parmentf commented on src/app/js/formats/lodex-field/LodexFieldView.js
> +            if (label == data.name) {
Perhaps clearer using [`find`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/find):
```js
return formatData[0].fields
    .find(data => data.name == label)
    .map((data, key) => (
        <div key={key}>
...
        </div>
    );
```

2018-06-18 09:04 UTC, parmentf approved these changes

2018-06-18 09:05 UTC, merged