[WIP]Fix catch format error
Inist-CNRS/lodex pull request #695
Opened 2018-09-21 07:45 UTC by ThieryMichel

2018-09-21 08:49 UTC, Kmaschta commented
Rebase needed please.

2018-09-21 12:06 UTC, ThieryMichel commented
rebased

2018-09-21 12:36 UTC, Kmaschta requested changes

2018-09-21 12:36 UTC, Kmaschta commented on src/app/js/formats/bubbleChart/BubbleView.js
> +export class BubbleView extends React.Component {
If this component doesn't have a state, we write it as a simple function

2018-09-21 12:36 UTC, Kmaschta commented on src/app/js/formats/heatmap/HeatMapView.js
> +export class HeatMapView extends Component {
Idem, if no state, prefer the usage of a function

2018-09-21 12:36 UTC, Kmaschta commented on src/app/js/formats/heatmap/HeatMapView.js
> +                                        data-tip={`${xKey},${yKey},${dictionary[
Can you move this logic into a named function?
It would be more clear IMO

2018-09-21 12:36 UTC, Kmaschta commented on src/app/js/formats/heatmap/HeatMapView.js
> +const mapDispatchToProps = {};
Just remove this variable and don't pass it to connect?

2018-09-24 08:50 UTC, Kmaschta approved these changes

2018-09-24 08:50 UTC, merged