[WIP] Fix composed field quick edition from frontend
Inist-CNRS/lodex pull request #709
Opened 2018-09-28 13:21 UTC by Kmaschta

[Trello card](https://trello.com/c/W36trY4p/11-les-modifications-de-valeurs-faites-%C3%A0-partir-de-la-page-daccueil-stylo-ne-sont-pas-prises-en-compte-dans-le-mod%C3%A8le-export%C3%A9-en-ad)

## TODO
- [x] Fix it
- [ ] Test it

2018-10-01 16:05 UTC, ThieryMichel requested changes

2018-10-01 16:05 UTC, ThieryMichel commented on Makefile
> +		db.publishedFacet.remove({}); \
:+1:

2018-10-01 16:05 UTC, ThieryMichel commented on src/api/controller/api/characteristic.js
> +        set(field, 'transformers[0].args[0].value', value),
Bad idea, set mutate the object.

2018-10-01 16:05 UTC, ThieryMichel commented on src/api/controller/api/characteristic.js
> +            const composedFields = await Promise.all(
use new findByNames method

2018-10-02 08:29 UTC, Kmaschta commented
Code review applied

2018-10-02 08:47 UTC, ThieryMichel requested changes

2018-10-02 08:47 UTC, ThieryMichel commented on src/api/controller/api/characteristic.js
> +    const copiedField = { ...field };
you need to deepClone the object

2018-10-02 09:02 UTC, Kmaschta commented
Bis :ok_hand:

2018-10-02 12:05 UTC, ThieryMichel approved these changes

2018-10-02 12:06 UTC, merged