[WIP] Test e2e field reorder
Inist-CNRS/lodex pull request #710
Opened 2018-09-28 16:06 UTC by ThieryMichel

2018-10-01 14:55 UTC, Kmaschta requested changes

2018-10-01 14:55 UTC, Kmaschta commented on cypress/integration/model.spec.js
> +            cy.visit('/');
Can you move all these useful fonctions into a proper support please?

2018-10-02 16:24 UTC, Kmaschta approved these changes

2018-10-02 16:25 UTC, Kmaschta requested changes

2018-10-03 07:46 UTC, ThieryMichel commented
I forced the langage to be english for test

2018-10-03 09:05 UTC, Kmaschta requested changes
English seems to not be enforced on my desktop.
Are you sure that the enforcement is working?

2018-10-04 09:45 UTC, ThieryMichel commented
fixed

2018-10-04 12:49 UTC, Kmaschta requested changes

2018-10-04 12:49 UTC, Kmaschta commented on cypress/integration/model.spec.js
> +        cy.get('.ontology-table-dataset h4').contains('Dataset');
This is not a test. You have to add a `.should` function to test something.

2018-10-04 12:49 UTC, Kmaschta commented on cypress/integration/model.spec.js
> +        cy.get('.ontology-table-dataset h4').contains('Dataset');
This is not a test. You have to add a `.should` function to test something.

2018-10-04 12:49 UTC, Kmaschta commented on cypress/integration/model.spec.js
> +        cy.get('.ontology-table-document h4').contains('Document');
This is not a test. You have to add a `.should` function to test something.

2018-10-04 12:49 UTC, Kmaschta commented on cypress/support/graphPage.js
> +        cy.get(`.dataset table thead th:nth-child(${index + 1})`).contains(col);
This is not a test. You have to add a `.should` function to test something.

2018-10-04 12:49 UTC, Kmaschta commented on cypress/support/homePage.js
> +        cy.get(`.property:nth-child(${index + 1})`).contains(name),
This is not a test. You have to add a `.should` function to test something.

2018-10-04 12:49 UTC, Kmaschta commented on cypress/support/modelPage.js
> +                `.ontology-table-${type} table tbody tr:nth-child(${index +
You can do better with this formatting..

2018-10-04 13:52 UTC, Kmaschta commented
La PR de Jouvence.

2018-10-04 16:09 UTC, Kmaschta approved these changes

2018-10-04 16:09 UTC, merged