try to improve seo
Inist-CNRS/lodex pull request #779
Opened 2018-11-02 18:04 UTC by touv

2018-11-06 10:29 UTC, Kmaschta reviewed
I don't get the point of displaying a link and a canonical link with a redirect.
Is this useful for the SEO or something?

2018-11-06 14:00 UTC, touv commented
Yes I try to improve SEO, for some resources that are just a redirection to a dedicated instance. For user, the redirect is (very) strange but finally, we access at the instance, For robot, it' not garantee, so if they can find a link in the page, I hope this one will be follow

for example : https://data.istex.fr/ark:/67375/84B-HKZV2R73-T

2018-11-07 08:28 UTC, ThieryMichel requested changes

2018-11-07 09:08 UTC, Kmaschta commented on src/app/js/formats/redirect/RedirectView.js
> +    const values = Array.isArray(value) ? value : [value];
I disagree with that. Reasonable defaults are way more useful than error logs.

2018-11-07 15:04 UTC, touv commented on src/app/js/formats/redirect/RedirectView.js
> +            <div className={className}>
why not, but I don't know what it is? Do you have examples?

2018-11-07 15:09 UTC, touv commented on src/app/js/formats/redirect/RedirectView.js
> +                <a href={url}>{url}</a>
Yes I understand. Ideally, we should have a server-side redirection. But now, it's the least bad solution

2018-11-07 15:18 UTC, ThieryMichel commented on src/app/js/formats/redirect/RedirectView.js
> +            <div className={className}>
https://reactjs.org/docs/fragments.html
It allow to have regroup children without rendering an additional div.
But I realize that in this case we need the className, so keep the div.

2018-11-07 15:19 UTC, ThieryMichel commented on src/app/js/formats/redirect/RedirectView.js
> +                <a href={url}>{url}</a>
Yes, but what I mean is that the link do nothing for seo, and would not help the user either  in the case of deactivated javascript IMHO.

2018-11-07 15:21 UTC, ThieryMichel commented on src/app/js/formats/redirect/RedirectView.js
> +                <a href={url}>{url}</a>
So just the helmet link should suffice.

2018-11-07 15:21 UTC, ThieryMichel commented on src/app/js/formats/redirect/RedirectView.js
> +            <div className={className}>
Unless you remove the <a>, in which case just return the <Helmet> directly.

2018-11-09 08:41 UTC, Kmaschta commented on src/app/js/formats/redirect/RedirectView.js
> +    const values = Array.isArray(value) ? value : [value];
@touv OK, after discussing with Thiery, we think it's better the display a `<InvalidFormat />` in case the value is an array.
Don't you think so?

2018-11-09 09:03 UTC, touv commented on src/app/js/formats/redirect/RedirectView.js
> +    const values = Array.isArray(value) ? value : [value];
Ok no problem

2018-11-12 08:39 UTC, Kmaschta approved these changes

2018-11-15 11:09 UTC, ThieryMichel approved these changes

2018-11-15 11:09 UTC, merged